version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - LLM_API_KEY=${LLM_API_KEY:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5001:8000"
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "5173:80"
