[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B", "SIM", "PLE" ]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["agents", "config", "storage"]
combine-as-imports = true
